from config.config import CHROMATIC_SCALE, NUM_STRINGS, STRING_LEN, FRETBOARD_LEN, NUM_FRETS, FRETS

__all__ = [

    "CHROMATIC_SCALE",
    "NUM_STRINGS",
    "STRING_LEN",
    "FRETBOARD_LEN",
    "NUM_FRETS",
    "FRETS"
    
]
